config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'home', to: 'home#index'

  resources :users, only: %i[new create]
  namespace :user do
    resources :email_confirmations, only: %i[new create]
    namespace :email_confirmations do
      post :resend
    end
    resources :password_reset_requests, only: %i[new create]
    resources :password_resets, only: %i[new create]
  end

  resource :user_session, only: %i[new create destroy]

  get 'log_in', to: redirect('/user_session/new')
  get 'sign_up', to: redirect('/users/new')
  delete 'log_out', to: 'user_sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

require 'securerandom'

class User < ApplicationRecord
  has_secure_password

  validates :username, :email, presence: true
  validates :email, uniqueness: true, confirmation: true
  validates :username, uniqueness: true

  attr_accessor :email_confirmation

  def start_email_confirmation
    return unless update(email_confirmation_token: SecureRandom.alphanumeric(20))

    UserMailer.with(user: self).email_confirmation_email.deliver_later
  end

  def start_password_reset
    return unless update(password_reset_token: SecureRandom.alphanumeric(20))

    UserMailer.with(user: self).password_reset_email.deliver_later
  end

  def email_confirmed?
    email_confirmation_token.blank?
  end
end

app/models/user/email_confirmation.rb
# frozen_string_literal: true

class User::EmailConfirmation
  include ActiveModel::Model

  attr_accessor :email_confirmation_token
end

app/models/user/password_reset.rb
# frozen_string_literal: true

class User::PasswordReset
  include ActiveModel::Model

  attr_accessor :password_reset_token, :password, :password_confirmation
end

app/models/user/password_reset_request.rb
# frozen_string_literal: true

class User::PasswordResetRequest
  include ActiveModel::Model

  attr_accessor :email_or_username
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/user/email_confirmations_controller.rb
# frozen_string_literal: true

class User::EmailConfirmationsController < ApplicationController
  def new
    @email_confirmation = User::EmailConfirmation.new(email_confirmation_params)
  end

  def create
    user = User.find_by(email_confirmation_token: params.dig(:user_email_confirmation, :email_confirmation_token))

    if user&.update(email_confirmation_token: nil)
      redirect_to :home, notice: 'Successfully confirmed your email address.'
    else
      redirect_to :home, alert: "Couldn't confirm your email address."
    end
  end

  def resend
    if helpers.logged_in? && helpers.current_user.start_email_confirmation
      redirect_to :home, notice: 'Please click the confirmation link in the email you will receive momentarily.'
    else
      redirect_to :home, alert: "Couldn't send confirmation email. Please try again later."
    end
  end

  private

  def email_confirmation_params
    params.require(:user_email_confirmation).permit(:email_confirmation_token)
  end
end

app/controllers/user/password_reset_requests_controller.rb
# frozen_string_literal: true

class User::PasswordResetRequestsController < ApplicationController
  def new
    @password_reset_request = User::PasswordResetRequest.new
  end

  def create
    email_or_username = password_reset_request_params[:email_or_username]
    user = User.where(username: email_or_username).or(User.where(email: email_or_username)).first

    user&.start_password_reset

    redirect_to :home, notice: 'Please click the password reset link in the email you will receive momentarily.'
  end

  private

  def password_reset_request_params
    params.require(:user_password_reset_request).permit(:email_or_username)
  end
end

app/controllers/user/password_resets_controller.rb
# frozen_string_literal: true

class User::PasswordResetsController < ApplicationController
  def new
    @password_reset = User::PasswordReset.new(password_reset_params)
  end

  def create
    user = User.find_by(password_reset_token: password_reset_params[:password_reset_token])

    if user&.update(user_password_params) && user&.update(password_reset_token: nil)
      # TODO: Should we inform the user by email that their password has been changed, in case it wasn't them?
      redirect_to :home, notice: 'Successfully changed your password.'
    else
      redirect_to :home, alert: "Couldn't update your password."
    end
  end

  private

  def password_reset_params
    params.require(:user_password_reset).permit(:password_reset_token)
  end

  def user_password_params
    params.require(:user_password_reset).permit(:password, :password_confirmation)
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:user_session][:username])

    if user&.authenticate(params[:user_session][:password])
      session[:current_user_id] = user.id
      redirect_to :home
    else
      @error = true
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to :home
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save && @user.start_email_confirmation
      redirect_to :home,
                  notice: 'Successfully signed up. Please click the confirmation link \
in the email you will receive momentarily.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :email_confirmation, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def logged_in?
    current_user.present?
  end

  def current_user
    User.find_by(id: session[:current_user_id])
  end
end

app/views/application/_errors.html.erb
<% if model.errors.any? %>
  <p>There were errors saving the <%= model.model_name.human %>:</p>

  <ul>
    <% model.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/application/_flashes.html.erb
<% if flash[:notice] %>
  <p class='notice'><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p class='alert'><%= flash[:alert] %></p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome</h1>

<% if logged_in? %>
  <% unless current_user.email_confirmed? %>
    <p>Please confirm your email address using the link in the email you received.</p>
    <%= button_to 'Resend confirmation email', user_email_confirmations_resend_path %>
  <% end %>

  <p>You are logged in as <%= current_user.username %>. <%= button_to 'log out', log_out_path, method: :delete %> </p>
<% else %>
  <p>You are not logged in.</p>
  <p>You can <%= link_to 'log in', log_in_path %> or <%= link_to 'sign up', sign_up_path %>.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationDemoRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'flashes' %>

    <%= yield %>
  </body>
</html>

app/views/user/email_confirmations/new.html.erb
<h1>Confirm your email</h1>

<%= form_for(@email_confirmation) do |f| %>
  <%= f.hidden_field :email_confirmation_token %>
  <%= f.submit 'Confirm' %>
<% end %>

app/views/user/password_reset_requests/new.html.erb
<h1>Reset your password</h1>

<%= form_for(@password_reset_request) do |f| %>
  <%= f.label :email_or_username, 'E-Mail or username' %>
  <%= f.text_field :email_or_username %>
  <%= f.submit 'Confirm' %>
<% end %>

app/views/user/password_resets/new.html.erb
<h1>Reset your password</h1>

<%= form_for(@password_reset) do |f| %>
  <%= f.hidden_field :password_reset_token %>

  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Password Confirmation' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Confirm' %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Log in</h1>

<% if @error %>
  <p>Couldn't log you in: Wrong username/password combination.</p>
<% end %>

<p>
  Did you forget your password? <%= link_to 'Reset password', new_user_password_reset_request_path %>
</p>

<%= form_for :user_session, url: user_session_path do |f| %>
  <%= f.label :username, "Username" %>
  <%= f.text_field :username %>

  <%= f.label :password, "Password" %>
  <%= f.password_field :password %>

  <%= f.submit "Log in", :disable_with => 'Logging in...' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'errors', model: @user %>

<%= form_for @user do |f| %>
  <%= f.label :email, 'E-Mail' %>
  <%= f.text_field :email %>

  <%= f.label :email_confirmation, 'E-Mail Confirmation' %>
  <%= f.text_field :email_confirmation %>

  <%= f.label :username, 'Username' %>
  <%= f.text_field :username %>

  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Password Confirmation' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Sign up', :disable_with => 'Signing up...' %>
<% end %>